name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show all ENV
        run: env

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/{{ github.repository_owner }}/coming-soon:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/{{ github.repository_owner }}/coming-soon:latest

      - name: Get Docker image
        run: |
          docker images
