name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'index.html'
      - 'nginx.conf'
      - '**.png'
      - '.github/workflows/docker-image.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase owner as environment variable
        run: |
          echo "REPO_OWNER_LC=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/$REPO_OWNER_LC/coming-soon:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/$REPO_OWNER_LC/coming-soon:latest

      - name: Get Docker image
        run: |
          docker images
